version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12.azerty
      MYSQL_DATABASE: AtlasVoteGate
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    image: atlasvotegate:latest
    container_name: atlasvotegate
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AtlasVoteGate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12.azerty

volumes:
  db_data:

networks:
  playground-network:
